basePath: /
definitions:
  entity.Category:
    properties:
      budget_limit:
        type: number
      created_at:
        type: string
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      type:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  entity.Transaction:
    properties:
      amount:
        type: number
      category:
        $ref: '#/definitions/entity.Category'
      category_id:
        type: integer
      created_at:
        type: string
      date:
        type: string
      description:
        type: string
      id:
        type: integer
      type:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
      wallet:
        $ref: '#/definitions/entity.Wallet'
      wallet_id:
        type: integer
    type: object
  entity.Wallet:
    properties:
      balance:
        type: number
      created_at:
        type: string
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      type:
        description: Bank, E-Wallet, Cash
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  service.CreateCategoryInput:
    properties:
      budget_limit:
        type: number
      icon:
        type: string
      name:
        type: string
      type:
        type: string
    required:
    - name
    - type
    type: object
  service.CreateTransactionInput:
    properties:
      amount:
        type: number
      category_id:
        type: integer
      date:
        type: string
      description:
        type: string
      type:
        description: income, expense
        type: string
      wallet_id:
        type: integer
    required:
    - amount
    - category_id
    - date
    - type
    - wallet_id
    type: object
  service.CreateWalletInput:
    properties:
      balance:
        type: number
      icon:
        type: string
      name:
        type: string
      type:
        type: string
      user_id:
        type: integer
    type: object
  service.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  service.RegisterInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  service.TransferTransactionInput:
    properties:
      amount:
        type: number
      date:
        type: string
      description:
        type: string
      from_wallet_id:
        type: integer
      to_wallet_id:
        type: integer
    required:
    - amount
    - date
    - from_wallet_id
    - to_wallet_id
    type: object
  service.UpdateCategoryInput:
    properties:
      budget_limit:
        type: number
      icon:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
  service.UpdateWalletInput:
    properties:
      balance:
        type: number
      icon:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for Petualangan Cuan Application
  title: Petualangan Cuan API
  version: "1.0"
paths:
  /api/categories:
    get:
      consumes:
      - application/json
      description: Get all categories for the logged in user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Category'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create a new category for transactions
      parameters:
      - description: Category Input
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/service.CreateCategoryInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.Category'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new category
      tags:
      - categories
  /api/categories/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete a category
      tags:
      - categories
    get:
      consumes:
      - application/json
      description: Get a specific category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Category'
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Get a category by ID
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update category details
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Category Input
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/service.UpdateCategoryInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Category'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update a category
      tags:
      - categories
  /api/transactions:
    get:
      consumes:
      - application/json
      description: Get all transactions for the logged in user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all transactions
      tags:
      - transactions
    post:
      consumes:
      - application/json
      description: Create a new income or expense transaction
      parameters:
      - description: Transaction Input
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/service.CreateTransactionInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.Transaction'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new transaction
      tags:
      - transactions
  /api/transactions/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a transaction by ID and revert balance
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete a transaction
      tags:
      - transactions
  /api/transactions/transfer:
    post:
      consumes:
      - application/json
      description: Create a transfer comprising an expense and an income
      parameters:
      - description: Transfer Input
        in: body
        name: transfer
        required: true
        schema:
          $ref: '#/definitions/service.TransferTransactionInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Transfer money between wallets
      tags:
      - transactions
  /api/wallets:
    get:
      description: Get all wallets for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all wallets
      tags:
      - wallets
    post:
      consumes:
      - application/json
      description: Create a new wallet for the authenticated user
      parameters:
      - description: Create Wallet Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.CreateWalletInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a new wallet
      tags:
      - wallets
  /api/wallets/{id}:
    delete:
      description: Delete a specific wallet
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Delete a wallet
      tags:
      - wallets
    get:
      description: Get a specific wallet by ID (must belong to user)
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get a wallet by ID
      tags:
      - wallets
    put:
      consumes:
      - application/json
      description: Update a specific wallet details
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Wallet Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.UpdateWalletInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update a wallet
      tags:
      - wallets
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login with email and password to get JWT token
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout current user (Invalidate token client-side)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Logout user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with name, email and password
      parameters:
      - description: Register Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.RegisterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - auth
swagger: "2.0"
